p8105_hw3_jl5934
================
Jesus Luevano
2023-10-06

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(p8105.datasets)
data("instacart")
data("brfss_smart2010")
```

# Problem 1

## Describing the dataset

- There are 1384617 rows and 15 columns in the `instacart` dataframe.

- The variables included are order_id, product_id, add_to_cart_order,
  reordered, user_id, eval_set, order_number, order_dow,
  order_hour_of_day, days_since_prior_order, product_name, aisle_id,
  department_id, aisle, department.

- There are 134 aisles in the dataframe.

``` r
instacart %>%
  group_by(aisle_id) %>%
  summarize(n_obs = n()) %>%
  arrange(desc(n_obs)) %>%
  head(3) %>%
  knitr::kable()
```

| aisle_id |  n_obs |
|---------:|-------:|
|       83 | 150609 |
|       24 | 150473 |
|      123 |  78493 |

- The top 3 aisles from where purchases are ordered from are Aisle 83
  (150609 purchases), 24 (150473 purchases), and 123 (78493 purchases).

``` r
instacart %>%
  group_by(aisle_id) %>%
  summarize(n_obs = n()) %>%
  filter(n_obs > 10000) %>%
  arrange(desc(n_obs)) %>%
  ggplot(aes(x = reorder(aisle_id, n_obs), y = n_obs)) +
  geom_bar(stat = "identity") +
  labs(x = "Aisle ID", 
       y = "Number Items Ordered",
       title = "Number of Items Ordered by Aisle if >1000 items") + 
  theme(axis.text.x = element_text(angle = 45))
```

![](p8105_hw3_jl5934_files/figure-gfm/plot%20aisles-1.png)<!-- -->

``` r
instacart %>%
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>% 
  group_by(aisle, product_name) %>%
  summarize(n_obs = n()) %>%  #count(product_name = "n_obs")
  arrange(desc(n_obs)) %>%
  slice_max(order_by = n_obs, n = 3) %>%
  knitr::kable()
```

    ## `summarise()` has grouped output by 'aisle'. You can override using the
    ## `.groups` argument.

| aisle                      | product_name                                  | n_obs |
|:---------------------------|:----------------------------------------------|------:|
| baking ingredients         | Light Brown Sugar                             |   499 |
| baking ingredients         | Pure Baking Soda                              |   387 |
| baking ingredients         | Cane Sugar                                    |   336 |
| dog food care              | Snack Sticks Chicken & Rice Recipe Dog Treats |    30 |
| dog food care              | Organix Chicken & Brown Rice Recipe           |    28 |
| dog food care              | Small Dog Biscuits                            |    26 |
| packaged vegetables fruits | Organic Baby Spinach                          |  9784 |
| packaged vegetables fruits | Organic Raspberries                           |  5546 |
| packaged vegetables fruits | Organic Blueberries                           |  4966 |

``` r
instacart %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  summarize(Mean = mean(order_hour_of_day, na.rm = TRUE)) %>%
  mutate(order_dow = case_match(
    order_dow, 0 ~ "Sunday", 1 ~ "Monday", 2 ~ "Tuesday", 3 ~ "Wednesday", 4 ~ "Thursday", 5 ~ "Friday", 6 ~ "Saturday"
  )) %>%
  pivot_wider(
    names_from = order_dow,
    values_from = Mean
  ) %>%
knitr::kable()
```

    ## `summarise()` has grouped output by 'product_name'. You can override using the
    ## `.groups` argument.

| product_name     |   Sunday |   Monday |  Tuesday | Wednesday | Thursday |   Friday | Saturday |
|:-----------------|---------:|---------:|---------:|----------:|---------:|---------:|---------:|
| Coffee Ice Cream | 13.77419 | 14.31579 | 15.38095 |  15.31818 | 15.21739 | 12.26316 | 13.83333 |
| Pink Lady Apples | 13.44118 | 11.36000 | 11.70213 |  14.25000 | 11.55172 | 12.78431 | 11.93750 |

# Problem 2

First we will set up our dataframe by reading in the `brfss_smart2010`,
cleaning the names, filtering based on `topic` being about “Overall
Health”, change the variable response to a factor, rename variables to
something more appropriate, and remove ones we will not need to work
with.

``` r
BRFSS <- brfss_smart2010 %>%
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>%
    mutate(response = response %>%
           fct_relevel("Poor", "Fair", "Good", "Very good", "Excellent")) %>%
  rename(overall_health = response, county = locationdesc, state = locationabbr, response_proportion = data_value) %>%
  select(-c(confidence_limit_high, confidence_limit_low, display_order, data_value_unit, data_value_type, data_value_footnote, data_value_footnote_symbol, class_id, topic_id, location_id, question_id, respid, geo_location))
```

``` r
BRFSS %>%
  filter(year == 2002) %>%
  distinct(state, year, county) %>%
  group_by(state) %>%
  summarize(n_obs = n()) %>%
  filter(n_obs >= 7) %>%
  knitr::kable()
```

| state | n_obs |
|:------|------:|
| CT    |     7 |
| FL    |     7 |
| MA    |     8 |
| NC    |     7 |
| NJ    |     8 |
| PA    |    10 |

- There are 7 states with more than 7 observations in 2002.

``` r
BRFSS %>%
  filter(year == 2010) %>%
  distinct(state, year, county) %>%
  group_by(state) %>%
  summarize(n_obs = n()) %>%
  filter(n_obs >= 7) %>%
  knitr::kable()
```

| state | n_obs |
|:------|------:|
| CA    |    12 |
| CO    |     7 |
| FL    |    41 |
| MA    |     9 |
| MD    |    12 |
| NC    |    12 |
| NE    |    10 |
| NJ    |    19 |
| NY    |     9 |
| OH    |     8 |
| PA    |     7 |
| SC    |     7 |
| TX    |    16 |
| WA    |    10 |

- There are 14 states with more than 7 observations in 2010.

``` r
BRFSS %>%
  janitor::clean_names() %>%
  filter(overall_health == "Excellent") %>%
  group_by(state, year) %>% 
  mutate(mean_response_prop = mean(response_proportion)) %>%
  select(year, state, mean_response_prop) %>%
  ggplot(aes(x = year, y = mean_response_prop)) + 
  geom_line(aes(color = state)) + 
  geom_smooth(method = "loess") +
  labs(x = "Year", y = "Mean Proportion Response", title = "Plot of mean proportion who responded Excellent to Overall Health by state over time")  
```

    ## `geom_smooth()` using formula = 'y ~ x'

    ## Warning: Removed 71 rows containing non-finite values (`stat_smooth()`).

    ## Warning: Removed 65 rows containing missing values (`geom_line()`).

![](p8105_hw3_jl5934_files/figure-gfm/average%20state%20excellent-1.png)<!-- -->

When plotting the mean values of `response_proportion` for the multiple
locations of a state, by year we are able to create a spaghetti plot
showing the changes from 2002-2010.

- When looking at the general trends across all the states, there does
  seem to be a downward proportion of those responding ‘Excellent’ that
  plateaus around 2005-2006 at 22%.

``` r
BRFSS %>%
  janitor::clean_names() %>%
  filter(year %in% c("2006", "2010"), state == "NY", topic == "Overall Health") %>%
  group_by(overall_health, county, year) %>%
  mutate(mean_response_prop = mean(response_proportion)) %>%
  ggplot(aes(x= county, y = mean_response_prop, fill = overall_health)) + 
  geom_bar(stat = "identity") +
  labs(x = "Overall Health Respones Level", y = "Proportion of Response", title = "Porportion of Respones to Overall health Question Among NY Counties for the years 2006 & 2010") +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.9)) +
  facet_grid(rows = vars(year))
```

![](p8105_hw3_jl5934_files/figure-gfm/data%20values%20for%20NY%20across%20years-1.png)<!-- -->

We have plotted the mean `data_value` for each location within NY (Bronx
County, Erie County, Kings County, Monroe County, Nassau County, New
York County, Queens County, Suffolk County, & Westchester County) for
the years 2006 and 2010 separately.

- Of note there were several counties without information in 2006:
  Bronx, Erie, Monroe.

- In general there seems to be a trend towards more ‘Poor’ health, and
  lower ‘Excellent’ health over time.

- Overall the majority of responess are within the ‘Good’ and ‘Very
  Good’ categories.

# Problem 3

We will import the dataframes from NHANES for the acceleratomer data
`accel.df` and demographic data `covar.df`. We will filter out subjects
from the demographic dataframe `covar.df` based on age (remove those
less than 21 years), remove those with missing demographic data, and
recode `education` and `sex` as appropriate factors.

We will then combine them by `inner_join` to select out only subjects
who met the inclusion criteria from the filters placed on `covar.df`.

``` r
accel.df <- read_csv("p8105_hw3_jl5934_files/data/nhanes_accel.csv") %>%
  janitor::clean_names()
```

    ## Rows: 250 Columns: 1441
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (1441): SEQN, min1, min2, min3, min4, min5, min6, min7, min8, min9, min1...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
covar.df <- read_csv("p8105_hw3_jl5934_files/data/nhanes_covar.csv",
                     skip = 4) %>%
  janitor::clean_names() %>%
  filter(age > 21) %>%
  na.omit() %>%
  mutate(education = as.factor(education) %>%
           fct_recode("Less_than_HS" = "1", "HS_equivalent" = "2", "More_than_HS" = "3")) %>%
  mutate(sex = as.factor(sex) %>% 
           fct_recode("male" = "1", "female" = "2"))
```

    ## Rows: 250 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (5): SEQN, sex, age, BMI, education
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
accel_covar.df <- inner_join(covar.df, accel.df, by = "seqn")
```

Producing a table for count of men and women in each education category.

``` r
accel_covar.df %>%
  group_by(sex, education) %>%
  summarize(n_obs = n()) %>%
  knitr::kable()
```

    ## `summarise()` has grouped output by 'sex'. You can override using the `.groups`
    ## argument.

| sex    | education     | n_obs |
|:-------|:--------------|------:|
| male   | Less_than_HS  |    27 |
| male   | HS_equivalent |    34 |
| male   | More_than_HS  |    54 |
| female | Less_than_HS  |    28 |
| female | HS_equivalent |    23 |
| female | More_than_HS  |    59 |

- For both Males and Females, the majority had education that was more
  than high school equivalent. However in second rank for Males was high
  school equivalent and last less then high school; whereas for Females
  it was less than high school in second rank then high school
  equivalent in last rank.

Next we will make a plot of age distribution by education level and sex.

``` r
accel_covar.df %>%
  group_by(sex, education) %>%
  ggplot(aes(x = age, fill = education)) +
  geom_boxplot() +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  labs(x = "Age in Years", title = "Age distribution of education levels by sex") +
  facet_grid(rows = vars(sex))
```

![](p8105_hw3_jl5934_files/figure-gfm/plot%20for%20table%20count%20by%20sex/education-1.png)<!-- -->

- For education level matched groups, the females seem to have a lower
  median age for more than HS, higher for HS equivalent, and very
  slightly lower age for less than HS.

- In both gender groups, there is a much small distribution of ages for
  the less than HS group compared to the other two. In addition, in both
  groups, the lowest age median is in the more than high school (for
  males the highest is less than HS, and for females the highest is HS
  equivalent)

Next we will make a plot that creates a new variable `Total_activity`
that is the aggregate of the total accelerometer readings for the
24-hour period for an individual.

``` r
accel_covar.df %>%
  mutate(total_activity = rowSums(.[6:1445])) %>%
  ggplot(aes(x = age, y = total_activity, color = sex)) +
  geom_point() + 
  geom_smooth(se= FALSE) +
  labs(x = "Age in years", y = "Total Activity", title = "Total activity by age, education, and sex") +
  scale_color_hue(direction = -1) +
  facet_grid(education ~ .)
```

    ## `geom_smooth()` using method = 'loess' and formula = 'y ~ x'

![](p8105_hw3_jl5934_files/figure-gfm/Total%20activity%20plot-1.png)<!-- -->

- This plot demonstrates that across all education levels and both
  genders, the total activity level decreases with age.

  - For lower education levels there is a trend towards higher overall
    levels of total activity until about age 60 where they all have a
    decrease.

  - In addition, females tend to have lower total activity levels across
    all education levels at younger ages, but this flips around 50 years
    for those with less than high school education.

<!-- -->

    ## `summarise()` has grouped output by 'minute', 'sex'. You can override using the
    ## `.groups` argument.
    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](p8105_hw3_jl5934_files/figure-gfm/24-insepction%20by%20eduation%20and%20sex-1.png)<!-- -->

- Looking at the plot, there are conserved trends of activity that
  starts to rise and plateau at around 7AM

- For every education level, males seem to have the higher average
  activity earlier one, but this trend reverses near 4AM and persists
  except for the less than high school education group that has some
  oscillations in which group has higher activity.

- Amongst the groups, less than HS education tends to have slightly
  higher average activity levels than the other groups, and more than HS
  the least particularly for males.
